repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed
        args: ["--maxkb=1024"]
      - id: check-ast # simply checks whether the files parse as valid python
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable
      - id: check-toml
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks
      - id: check-yaml # checks yaml files for parseable syntax
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
      #      - id: detect-aws-credentials  # detects *your* aws credentials from the aws cli credentials file
      - id: detect-private-key # detects the presence of private keys
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
        files: ^.*py$
      - id: mixed-line-ending # replaces or checks mixed line ending
        files: ^.*py$
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: requirements-txt-fixer # sorts entries in requirements.txt
      - id: trailing-whitespace # trims trailing whitespace
        files: ^.*py$

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 .
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort .
        language: python
        files: ^.*py$

      - id: nbdev
        name: nbdev clean
        entry: nbdev_clean --clear_all
        pass_filenames: false
        language: python
        files: .ipynb

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        files: ^.*py$

      - id: vulture
        name: vulture
        entry: vulture
        args: ["--min-confidence", "61"]
        language: python
        files: ^.*py$
